eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10322/eureka
  instance:
    prefer-ip-address: true

# redis 사용 시
spring:
  data:
    redis:
      host: localhost
      port: 6379